[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Nathan Ens<n.ens.edu@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "pypdf>=5.1.0",
    "requests>=2.32.3",
]
